defaults:
  - model: pan
  - data/data_common
  - data/generator
  - data/transmitter
  - data/rm_module
  - trainer: default
  - test: null
  - _self_

# Hydra settings
hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}

# Experiment settings
seed: 42
work_dir: ${oc.env:PWD}

# Paths
data_dir: ${work_dir}/src/poc/processed_data
save_dir: ${work_dir}/outputs   # where to save logs, checkpoints, etc.